@startuml Seller Antiquarian
entity Books {
    + bookId: UUID /'primary key, globally unique'/
    + isbn: text /'unique for same edition of book'/
    + sellerId: int /'foreign key'/
    + status: enum /'available, reserved, sold'/
    + price: numeric
    + title: text
    + author: text
    + year: int
    + type: text
    + genre: text
    + mass: numeric
    + buyInPrice: numeric
    + soldDate: timestamptz
}
@enduml
