export const DEFAULTS = {
    users: [
        {
            userid: 'admin@arkkidivari.com',
            role: 'admin',
            password: 'admin123',
            name: 'Järjestelmänvalvoja',
            address: 'Koulukatu 1',
            zip: '33100',
            city: 'Tampere',
            phone: '0451098765',
        },
        {
            userid: 'lasse@lassenlehti.fi',
            role: 'seller',
            password: 'lasse456',
            name: 'Lasse Lehtinen',
            address: 'Satamakatu 14',
            zip: '33200',
            city: 'Tampere',
            phone: '0401234567',
        },

        {
            userid: 'galle@galeinngalle.fi',
            role: 'seller',
            password: 'galle789',
            name: 'Galle Galleinn',
            address: 'Pasilanraitio 11',
            zip: '00240',
            city: 'Helsinki',
            phone: '0507654321',
        },
        {
            userid: 'kimmo@kirjakammio.fi',
            role: 'seller',
            password: 'kimmoEiKestäKakaroitaan',
            name: 'Kimmo Kammio',
            address: 'Mannerheimintie 10',
            zip: '00100',
            city: 'Helsinki',
            phone: '094321',
        },
    ],
    books: [
        {
            isbn: '9155430674',
            title: 'Elektran tytär',
            author: 'Madeleine Brent',
            year: 1986,
            weight: 320,
            typeid: 1,
            genreid: 5,
        },
        {
            isbn: '9156381451',
            title: 'Tuulentavoittelijan morsian',
            author: 'Madeleine Brent',
            year: 1978,
            weight: 512,
            typeid: 1,
            genreid: 5,
        },
        {
            isbn: null,
            title: 'Turms kuolematon',
            author: 'Mika Waltari',
            year: 1995,
            weight: 320,
            typeid: 1,
            genreid: 6,
        },
        {
            isbn: null,
            title: 'Komisario Palmun erehdys',
            author: 'Mika Waltari',
            year: 1940,
            weight: 180,
            typeid: 1,
            genreid: 3,
        },
        {
            isbn: null,
            title: 'Friikkilän pojat Mexicossa',
            author: 'Shelton Gilbert',
            year: 1989,
            weight: 80,
            typeid: 2,
            genreid: 10,
        },
        {
            isbn: '9789510396230',
            title: 'Miten saan ystäviä, menestystä, vaikutusvaltaa',
            author: 'Dale Carnegien',
            year: 1939,
            weight: 320,
            typeid: 3,
            genreid: 11,
        },
    ],
};
